# Content Area ----
content_area_sites <- c("NY_D9", "NY_D12", "NY_D13", "NY_D16")
usethis::use_data(content_area_sites, overwrite = TRUE)

# Subsites ----
# Maps qualtrics variable names to L&R site names
subsites <- current_subsites |>
  setNames(c("AR_Osceola School District",
             "CA_Santa Ana Unified School District",
             "IL_CPS",
             "NY_D6", "NY_D6 Other",
             "NY_D9", "NY_D9 Other",
             "NY_D11", "NY_D11 Other",
             "NY_D12", "NY_D12 Other",
             "NY_D13", "NY_D13 Other",
             "NY_D16", "NY_D16 Other",
             "NY_D17", "NY_D17 Other",
             "NY_D25", "NY_D25 Other",
             "NY_D75", "NY_D75 Other",
             "MA_Boston",
             "MA_Dennis-Yarmouth",
             "MA_Milford",
             "MA_Plymouth",
             "MA_Uxbridge",
             "MA_West Springfield",
             "MS_Kemper County School District",
             "NJ_Great Oaks Legacy Charter Schools",
             "NY_Ascend Charter Schools",
             "NY_CUNY/UA",
             "NY_LION Charter Schools",
             "NY_Transfer High Schools",
             "TN_Acceleration for All",
             "TN_Acceleration for All",
             "TX_El Paso Leadership Academy",
             "TX_La Joya ISD",
             "WI_Milwaukee Public Schools"))
usethis::use_data(subsites, overwrite = TRUE)

subsites <- current_subsites |>
  setNames(c("AR_Osceola School District",
             "CA_Santa Ana Unified School District",
             "IL_CPS",
             "NY_D6", "NY_D6 Other",
             "NY_D9", "NY_D9 Other",
             "NY_D11", "NY_D11 Other",
             "NY_D12", "NY_D12 Other",
             "NY_D13", "NY_D13 Other",
             "NY_D16", "NY_D16 Other",
             "NY_D17", "NY_D17 Other",
             "NY_D25", "NY_D25 Other",
             "NY_D75", "NY_D75 Other",
             "MA_Boston",
             "MA_Dennis-Yarmouth",
             "MA_Milford",
             "MA_Plymouth",
             "MA_Uxbridge",
             "MA_West Springfield",
             "MS_Kemper County School District",
             "NJ_Great Oaks Legacy Charter Schools",
             "NY_Ascend Charter Schools",
             "NY_CUNY/UA",
             "NY_LION Charter Schools",
             "NY_Transfer High Schools",
             "TN_Acceleration for All",
             "TN_Acceleration for All",
             "TX_El Paso Leadership Academy",
             "TX_La Joya ISD",
             "WI_Milwaukee Public Schools"))
usethis::use_data(subsites, overwrite = TRUE)

subsites_24_25 <- c("ar_blytheville",
              "ar_friendship",
              "ar_hope",
              "ar_osceola",
              "ca_santa_ana",
              "dennis_yarm",
              "il_cps",
              "district6",
              "district6_other",
              "district7",
              "district7_other",
              "district9",
              "district9_other",
              "district11",
              "district11_other",
              "district12",
              "district12_other",
              "district13",
              "district13_other",
              "district16",
              "district16_other",
              "district17",
              "district17_other",
              "district25",
              "district25_other",
              "district27",
              "district27_other",
              "district75",
              "district75_other",
              "east_harlem",
              "la_pointe_coupee",
              "ma_dese",
              "ma_boston",
              "ma_milford",
              "ma_plymouth",
              "ma_uxbridge",
              "ma_westspring",
              "ms_kemper",
              "nc_charlotte",
              "network4",
              "network7",
              "network12",
              "nj_great_oaks",
              "nm_nm_ped",
              "ny_ascend",
              "ny_cuny",
              "ny_lion",
              "ny_transfer",
              "oh_cleveland",
              "rochester",
              "tn_acceleration",
              "tn_acceleration2",
              "tx_elpaso",
              "wi_milwaukee",
              "wi_victory") |>
  setNames(c("AR_Blytheville School District", "AR_Friendship Aspire Academy", "AR_Hope Public Schools", "AR_Osceola School District",
             "CA_Santa Ana Unified School District",
             "Dennis-Yarmouth",
             "IL_CPS",
             "NY_D6", "NY_D6 Other",
             "NY_D7", "NY_D7 Other",
             "NY_D9", "NY_D9 Other",
             "NY_D11", "NY_D11 Other",
             "NY_D12", "NY_D12 Other",
             "NY_D13", "NY_D13 Other",
             "NY_D16", "NY_D16 Other",
             "NY_D17", "NY_D17 Other",
             "NY_D25", "NY_D25 Other",
             "NY_D27", "NY_D27 Other",
             "NY_D75", "NY_D75 Other",
             "NY_East Harlem Scholar Academies (EHTP)",
             "LA_Pointe Coupee Parish",
             "MA_DESE",
             "MA_Boston",
             "MA_Milford",
             "MA_Plymouth",
             "MA_Uxbridge",
             "MA_West Springfield",
             "MS_Kemper County School District",
             "NC_Charlotte-Mecklenburg Schools",
             "IL_Chicago Public Schools_Network 4",
             "IL_Chicago Public Schools_Network 7",
             "IL_Chicago Public Schools_Network 12",
             "NJ_Great Oaks Legacy Charter Schools",
             "NM_NM Public Education Department",
             "NY_Ascend Charter Schools",
             "NY_CUNY/UA",
             "NY_LION Charter Schools",
             "NY_Transfer High Schools",
             "OH_Cleveland Metro School District",
             "NY_Rochester City Schools",
             "TN_Acceleration for All",
             "TN_Acceleration for All",
             "TX_El Paso Leadership Academy",
             "WI_Milwaukee Public Schools",
             "WI_Victory"))
usethis::use_data(subsites_24_25, overwrite = TRUE)
